AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - spec/**/*

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Max: 90

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - base_feature
    - build
    - configuration
    - define_helpers
    - define_list_feature
    - define_list_item_feature
    - define_simple_feature
    - factory
    - sv_rtl
    - sv_ral

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
