# frozen_string_literal: true

require 'docile'

require_relative 'basic_output_components/version'

require_relative 'basic_output_components/systemverilog_utility/identifier'
require_relative 'basic_output_components/systemverilog_utility/data_object'
require_relative 'basic_output_components/systemverilog_utility/interface_port'
require_relative 'basic_output_components/systemverilog_utility/interface_instance'
